### PR TITLE
WIP: add Freesurfer files to data tests

### PR DESCRIPTION
**Pull request by matthew-brett**
Add Freesurfer files to git submodule to run Freesurfer tests on travis.

There are currently failing tests - for recent numpy:

```
======================================================================
FAIL: Test IO of .annot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
      self.test(*self.arg)
        File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.6/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
            return f(*args, **kwargs)
              File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.6/site-packages/nibabel/freesurfer/tests/test_io.py", line 101, in test_annot
                  assert_true(np.sum(labels_orig == 0) > 0)
                  AssertionError
```

For numpy 1.5:

```
======================================================================
ERROR: Test IO of .annot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
      self.test(*self.arg)
        File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
            return f(*args, **kwargs)
              File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.7/site-packages/nibabel/freesurfer/tests/test_io.py", line 93, in test_annot
                  labels, ctab, names = read_annot(annot_path)
                    File "/home/travis/build/matthew-brett/nibabel/venv/lib/python2.7/site-packages/nibabel/freesurfer/io.py", line 233, in read_annot
                        labels[mask] = ord[np.searchsorted(ctab[ord, -1], labels[mask])]
                        TypeError: array cannot be safely cast to required type
```

See : https://travis-ci.org/matthew-brett/nibabel/builds/56546692

### CODE REVIEW

**Comment by matthew-brett** [comment]
@agramfort @ohinds - any thoughts?

**Comment by agramfort** [comment]
LGTM !

thanks @matthew-brett

**Comment by matthew-brett** [comment]
Sorry Alex - I meant also - any thoughts about the test failures?

**Comment by matthew-brett** [comment]
@agramfort  - sorry to pester - do you have any time to look at this one?

**Comment by agramfort** [comment]
@matthew-brett for the test "assert_true(np.sum(labels_orig == 0) > 0)" it's a problem with the lh.aparc.annot file you ship. It's different from the one I have with freesurfer 5.

For the pb with numpy 1.5 I cannot reproduce :(

**Comment by Eric89GXL** [comment]
@matthew-brett if you can reproduce locally, can you say what the incompatibly types are? If not, you could push a tiny commit to Travis to print out the types on failure.

Perhaps updating the annotation file will magically fix both problems, though.

**Comment by matthew-brett** [comment]
Alex - I just downloaded `fasverage.tar.gz` from https://surfer.nmr.mgh.harvard.edu/ftp/data

The copy of `lh.aparc.annot` in the test archive is the same as the copy in that archive.  Is it possible your copy is out of date?

**Comment by agramfort** [comment]
not idea. I am fine updating the test if you think it's best. Just let me
know

**Comment by matthew-brett** [comment]
Yes, please do update the test to work with the current version.   Maybe we should do something to check the file version (different test values for different sha1 hashes of the input file)?

**Comment by agramfort** [comment]
closing in favor of #307

**Pull request closed without merging**
