### PR TITLE
Ignore unreadable siemens private headers

### PR DESCRIPTION
**Pull request by hbraunDSP**
Workaround for #812. 
dicomwrappers.py will catch and recover from a `CSAReadError` in csarereader.py, setting `csa=None` and giving a warning.  This allows use on some dicoms with CSA headers that are unreadable by nibabel, either because they are corrupted or not supported yet.

### CODE REVIEW

**Comment by effigies** [comment]
@hbraunDSP Is this still a WIP? If you can find a test file, that'd be great. Feel free to submit to https://github.com/effigies/nitest-dicom/.

**Comment by hbraunDSP** [comment]
It should be good to go...I'll be sending a file for testing soon. Thanks for the reminder!

**Comment by effigies** [comment]
We'll need to update `nitest-dicom` in https://github.com/nipy/nibabel/tree/master/nibabel-data:

```Shell
git submodule init
git submodule sync
git submodule update
git -C nibabel-data/nitest-dicom fetch
git -C nibabel-data/nitest-dicom checkout origin/master
git add nibabel-data/nitest-dicom
```

Then we'll need to add the new file as follows:

https://github.com/nipy/nibabel/blob/ddf26830eebdb11470009c3a04047377f29a4732/nibabel/nicom/tests/test_dicomwrappers.py#L40-L41

And test it similar to the following:

https://github.com/nipy/nibabel/blob/ddf26830eebdb11470009c3a04047377f29a4732/nibabel/nicom/tests/test_dicomwrappers.py#L628-L634

**Comment by effigies** [comment]
@hbraunDSP Just a bump on these tests. If you don't have time, I can make a quick PR to your branch.

**Comment by effigies** [comment]
See hbraunDSP#2.

**Comment by hbraunDSP** [comment]
I can't really look at this until Wednesday, sorry

**Comment by effigies** [comment]
I think this is good as-is, and we're now getting full diff coverage (thanks!). Feel free to open a new PR if there's anything else you'd like to update...

**Pull request merged**
