### PR TITLE
RF+API: add qform, sform code 1 for parrec2nii

### PR DESCRIPTION
**Pull request by matthew-brett**
As discussed in https://github.com/nipy/nibabel/pull/478

### CODE REVIEW

**Comment by effigies** [comment]
LGTM.

**Comment by effigies** [comment]
Can't really comment on the Mock stuff, but as far as I can see it's fine. @ilogue, can you have a look?

**Comment by ilogue** [comment]
LGTM

**Comment by matthew-brett** [comment]
Thanks for reviews - merging.

**Pull request merged**
