### PR TITLE
FIX: Correctly cast ``nan`` when testing ``array_to_file``- fixes ARM64 builds

### LINKED ISSUE #861: Test failure on Arm64
Unfortunately I can't debug since I don't have such a machine set up; the tests were run by Hydra, the CI server for Nix/Nixpkgs for [this PR](https://github.com/NixOS/nixpkgs/pull/77472).

Release 3.0.0.

```
FAIL: nibabel.tests.test_volumeutils.test_a2f_nan2zero_range
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/iqysj9ccwz5xww339z07jyl6k5zc5074-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/nibabel-3.0.0/nibabel/tests/test_volumeutils.py", line 675, in test_a2f_nan2zero_range
    assert_array_equal([-128, -128, -128, nan_cast], back_arr)
  File "/nix/store/7k6dbm0p5imsnivp1xshbzkj30i28cjq-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/nix/store/7k6dbm0p5imsnivp1xshbzkj30i28cjq-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Mismatched elements: 1 / 4 (25%)
Max absolute difference: 1
Max relative difference: 1.0
 x: array([-128, -128, -128,    0])
 y: array([-128, -128, -128,   -1], dtype=int8)
----------------------------------------------------------------------
Ran 7671 tests in 227.364s
```

### PR DESCRIPTION
**Pull request by effigies**
Trying to replicate #861.

Closes #861.

### CODE REVIEW

**Comment by effigies** [comment]
According to https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures, we can also check on `ppc64le` and `s390x`. Will look into those if this works smoothly.

**Comment by effigies** [comment]
@matthew-brett The ARM64 jobs require building numpy from source every time. Would it be reasonable to open a PR against numpy-wheels to add non-x86 wheels to their .travis.yml? Would anything else be required apart from updating multibuild?

**Comment by kaczmarj** [comment]
can you use miniconda? there are arm64 and powerpc miniconda installations, and numpy is compiled for arm64 and powerpc (https://anaconda.org/conda-forge/numpy).

**Comment by effigies** [comment]
Numpy is working on wheels on their end. I don't think it's too urgent to wait on that.

**Comment by effigies** [comment]
Anybody up for a review? Will merge Friday if nobody shouts.

**Comment by matthew-brett** [comment]
Looks right to me - thanks for tracking that down.

**Comment by effigies** [comment]
Great, thanks for having a look.

**Pull request merged**
