### PR TITLE
NF: add version of Paul Ivanov's slice viewer

### PR DESCRIPTION
**Pull request by matthew-brett**
@ivanov - many thanks for this - it's very nice, and very useful.

The thing I really miss though, is having cross-hairs showing me the
corresponding current point on all three panels.

I think there's an example here:

http://marsbar.sourceforge.net/_images/roi_view.png

I experimented for a while trying to put the crosshairs on, but it was beyond
my blit fu.  Any pointers as to how to do that?  I mean, put up the
cross-hairs, different on every movement of the slices, but still be able to
blit for speed?

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Should close this given `nilearn` has something similar, or you think it's still worth pursuing here?

http://nilearn.github.io/building_blocks/plotting.html

**Comment by matthew-brett** [comment]
Sorry to be lazy - but at a first pass these all looked static - so you can't click around the image?

**Comment by Eric89GXL** [comment]
It was dynamic last time I used it, clicking around the image should work as should linking two images together, etc. IIRC everything was working correctly when we last looked at it, we just shelved it due to the release and concerns that it should be part of the resampling PR, e.g.:

https://github.com/matthew-brett/nibabel/pull/5#issuecomment-61022377

**Comment by matthew-brett** [comment]
Sorry - I mean the nilearn stuff is static - no?  If that is true, this PR still does something we need and that we don't have.

**Comment by Eric89GXL** [comment]
That's true. Do you think it's worth trying to port our changes over to their code instead of partially duplicating effort? That might be a pain, though, I guess.

How's the resampling coming along? :)

**Comment by matthew-brett** [comment]
Hi Eric.  @choldgraf just caught me in the corridor asking about this one.

I would like to get this merged real-soon-now (TM).    I need this stuff too.  I think we can sort out the resampling axis stuff later.   Do you have some time to rebase this?  I've got quite a bit of time in the next few days to do final review.

**Comment by Eric89GXL** [comment]
That was quick, nicely done @choldgraf :)

I should be able to look tomorrow.

**Comment by Eric89GXL** [comment]
Closing for #404

**Pull request closed without merging**
