### PR TITLE
MRG: fix for doctest errors on Python 3.5

### PR DESCRIPTION
**Pull request by matthew-brett**

### CODE REVIEW

**Comment by bcipolli** [comment]
I don't understand this deeply, but at a surface level LGTM. 

Should we enable Travis tests on Python 3.5 here to check that this solves Python 3.5 issues?

**Comment by matthew-brett** [comment]
Good idea for the tests.

**Comment by bcipolli** [comment]
@matthew-brett got stuck at the installation phase: 
image

**Comment by matthew-brett** [comment]
Thanks for the review - in it goes.

**Pull request merged**
