### PR TITLE
DOC Use HTTPS for outside scripts/forms

### PR DESCRIPTION
**Pull request by effigies**
Since `*.github.io` pages support HTTPS, pulling in content from HTTP addresses causes browsers to complain about unsafe scripts. This eliminates any warnings, on a test I ran on one of our lab web servers. Loading scripts over HTTPS from an HTTP connection shouldn't cause problems.

HTTPS might not be a priority for nibabel, so I limited this initial commit to making the nibabel site eliminate browser warnings. If it would be welcome, I can also go through other URLs throughout the documentation and upgrade them to HTTPS when they exist and have a valid certificate.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Yes, sure - go wild on https :)​

**Comment by effigies** [comment]
Well, a little less important now I see that https://nipy.github.io will be redirecting to the HTTP-only http://nipy.org, but I can go ahead and do this.

How should I treat dead links? If I can find a new location, I'll change to that, but if not, should I leave them as is, mark as dead somehow, or remove them entirely?

**Comment by matthew-brett** [comment]
Why not remove them, and we'll all have a go at trying to find replacements
while we're reviewing the PR.​

**Comment by matthew-brett** [comment]
Nice - thanks very much for doing that.

**Pull request merged**
