### PR TITLE
Siemens CSA Reader: Increase maximum number of items

### PR DESCRIPTION
**Pull request by isolovey-robarts**

### CODE REVIEW

**Comment by effigies** [comment]
This seems fine to me.

A limit of 99 was added by @matthew-brett in 59dc04a96718cf8dd0cf36658daafab86bc22886 and updated to 199 by @kevlarkevin in #242. Could one or both of you chime in on the original intent, and whether it makes sense to keep a fixed limit at all?

@isolovey-robarts In any event, you may want to update the test added in #242.

**Comment by matthew-brett** [comment]
No principled reason for the number, just there to avoid getting locked into parsing a broken header into the rest of the filesystem.

**Comment by isolovey-robarts** [comment]
Kept the limit at 1000 and fixed the tests.

**Comment by effigies** [comment]
Please merge master to fix style checks.

**Comment by effigies** [comment]
I agree. Thanks!

**Pull request merged**
