### PR TITLE
DEBUG: Revert to pre-error trees and enable AppVeyor debugging

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Restart a few times?

**Comment by effigies** [comment]
https://ci.appveyor.com/project/nipy/nibabel/builds/19485598/job/cxp38t30ee2aylci

**Comment by effigies** [comment]
Restarted, because there were files added during these intervals that don't get removed with `git checkout <githash> .`. That needs to be followed by a `git checkout -p <githash> .`.

Two targets are dfd113c531ad0dbb301db919b8573ad12ae0bb56 (Jun 4) and 68cf6715cf7977f597f3d6b743467a46e8d397c0 (Apr 24).

4 build attempts on each.

**Comment by effigies** [comment]
Ah, this may be relevant:

screen shot 2018-10-15 at 07 04 14

I think next step should be to try a range of Numpy versions, starting from 1.14.2 or so.

**Comment by effigies** [comment]
Error from dfd113c531ad0dbb301db919b8573ad12ae0bb56 reversion: https://ci.appveyor.com/project/nipy/nibabel/builds/19518274/job/24o3p60j85fu6g7j

**Comment by effigies** [comment]
Yes! Failure at last! So it's not our fault. I'll iterate over numpy releases next.

cc @yarikoptic

**Comment by effigies** [comment]
Problem reproduces in numpy 1.14.2: https://ci.appveyor.com/project/nipy/nibabel/builds/19582043/job/8iuss25ktq30hqde?fullLog=true

Will push back a few versions, just to be sure.

**Comment by yarikoptic** [comment]
whoohoo -- what a fishing expedition ;-) "love it"!

**Comment by yarikoptic** [comment]
grr... only 1.12 fails similarly ... so either it is even before then, or not numpy fault

**Comment by effigies** [comment]
Looks like probably not numpy's fault.

**Comment by nibotmi** [comment]
:umbrella: The latest upstream changes (presumably #700) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by effigies** [comment]
This effort is dead. The bug seems to be happening less lately, so hopefully whatever was going on over at AppVeyor is resolved. I think if this recurs, we should think about moving to Azure Pipelines for Windows tests.

**Pull request closed without merging**
