### PR TITLE
WIP: testing the new homu bot

### PR DESCRIPTION
**Pull request by matthew-brett**
Here I'm testing a new homu bot instance running on the nipy server.

See: https://github.com/barosl/homu and http://homu.io for more detail.

I'm going to try running a few homu commands to see whether they work.

### CODE REVIEW

**Comment by matthew-brett** [comment]
@nibotmi r+

**Comment by nibotmi** [comment]
:pushpin: Commit b30b8c5 has been approved by `matthew-brett`

**Comment by nibotmi** [comment]
:hourglass: Testing commit b30b8c5 with merge cc22a99...

**Comment by matthew-brett** [comment]
This is another bot command:

@nibotmi r-

**Comment by matthew-brett** [comment]
@nibotmi r-

**Comment by matthew-brett** [comment]
I think this one is OK to go:

@nibotmi r+

**Comment by nibotmi** [comment]
:pushpin: Commit b96d6d6 has been approved by `matthew-brett`

**Comment by nibotmi** [comment]
:hourglass: Testing commit b96d6d6 with merge 5970787...

**Comment by nibotmi** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/nipy/nibabel/builds/103954159)

**Pull request merged**
