### PR TITLE
MincHeader.get_xyzt_units()

### PR DESCRIPTION
**Pull request by jennydaman**
The headers of MINC files have information which specifies the volume units (almost always mm). This PR exposes the data via `MincHeader.get_xyzt_units()`, which is homologous to `Nifti1Header.get_xyzt_units()`. But I don't work with 4D MINC so the 't' unit is simply `"unknown"`.

I'm thinking that it would be nice to have `get_xyzt_units()` part of the header interface.

This PR is kind of a draft? It works, though my intention is to open a discussion and perhaps support `get_xyzt_units()` for other file formats too.

### CODE REVIEW

**Comment by jennydaman** [comment]
Possibly convergent work: https://github.com/nipy/nibabel/pull/567

**Comment by jennydaman** [comment]
@effigies PTAL?

**Comment by effigies** [comment]
Sorry, what does PTAL mean?

**Comment by jennydaman** [comment]
Please Take A Look (which you just did)

**Comment by effigies** [comment]
I assume you're seeing (in the CI output):

```
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  nibabel/tests/test_image_api.py:234: in validate_data_interface
      img = imaker()
  nibabel/tests/test_image_api.py:608: in <lambda>
      yield lambda: self.loader(img_params['fname']), img_params
  nibabel/dataobj_images.py:504: in from_filename
      return klass.from_file_map(file_map, mmap=mmap, keep_file_open=keep_file_open)
  nibabel/minc1.py:353: in from_file_map
      units = minc_file.get_units()
  nibabel/minc1.py:117: in get_units
      return tuple(d.units.decode('utf-8') for d in self._dims)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  .0 = <list_iterator object at 0x7f929c3f3700>
  
  >   return tuple(d.units.decode('utf-8') for d in self._dims)
  E   AttributeError: 'netcdf_variable' object has no attribute 'units'
```

**Comment by jennydaman** [comment]
Whoops. Looks like too much has changed in the past 2 years and this PR isn't going to work anymore.

Could we continue the conversation in #1116? If we decide `get_xyzt_units` is a desirable feature to have, I can look into how to support it for MINC.

**Pull request closed without merging**
