### PR TITLE
MRG: fix Python 2, old Sympy stuff in derivations

### PR DESCRIPTION
**Pull request by matthew-brett**
Python 2 prints, and older uses of Sympy.

Found while checking #910

### CODE REVIEW

**Comment by jond01** [comment]
Hi, I suggest also changing `slice_thickness` and its occurrences here:
https://github.com/nipy/nibabel/blob/8471a3701332c9ec08c51e153cc88551355af1b0/doc/source/dicom/derivations/spm_dicom_orient.py#L40

To `slice_spacing`, in order to avoid confusion with the *Slice Thickness* dicom attribute.

**Comment by matthew-brett** [comment]
Good point, thanks.

**Comment by effigies** [comment]
The failing style check should be fixed in master. Mind hitting the PEP8 fixes requested by pep8speaks?

**Comment by matthew-brett** [comment]
I did a rebase to get rid of the PEP8 errors - but now get a coverage error - it must be a false positive.

**Comment by effigies** [comment]
Yeah, Codecov is overly sensitive. I'm okay to merge, if you're all set.

**Comment by matthew-brett** [comment]
All set.

**Pull request merged**
