### PR TITLE
ENH: Add ndim to ArrayProxy and DataobjImage

### LINKED ISSUE #595: DataobjImage doesn't proxy ndim
`DataobjImage` currently [proxies `shape`](https://github.com/nipy/nibabel/blob/6eacaf556c31c62f698ac07b4112245842d21f4e/nibabel/dataobj_images.py#L391-L393) but not [`ndim`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html) even though various docs refer to `ndim(s)`: 
* http://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Header.set_data_shape
* http://nipy.org/nibabel/reference/nibabel.nifti2.html#nibabel.nifti2.Nifti2Header.set_data_shape

Might be useful to proxy `ndim` through.

### PR DESCRIPTION
**Pull request by effigies**
Closes #595.

### CODE REVIEW

**Comment by effigies** [comment]
@cancan101 Would you like to test that this provides the interface(s) you were asking for?

**Comment by effigies** [comment]
@matthew-brett Up for a quick review? This is a pretty small change.

**Comment by matthew-brett** [comment]
Thanks - yes - it looks fine.  The only question is whether it's really worth adding the code for the benefit of going from `ndim = dataobj.ndim` to `ndim = len(dataobj.shape)`.    What do you think?

**Comment by effigies** [comment]
I agree it's trivial. The advantage of the addition to ArrayProxy is that now ndim exists regardless of how the image is created. It's just a least surprise sort of thing. Passing it though to the image itself is less obviously simplifying, but what #595 originally asked about, so I went ahead and included it.

**Comment by matthew-brett** [comment]
Then I'm fine with it, if you are ...

**Pull request merged**
