### PR TITLE
FIX: Ensure loaded GIFTI files expose writable data arrays

### LINKED ISSUE #746: Cannot set values in GIFTI data array loaded from file
Dear numpy experts, 

I am running fmriprep on singularity with a version 3.01 image

and my whole 76 subjects dataset run in parallel are crashing on our HPC and give this error message: 

"
Node: 
fmriprep_wf.single_subject_109_wf.func_preproc_ses_1_task_restingstate_wf.bold_surf_wf.medial_nans
Working directory: /mnt/data/loic2/work/fmriprep_wf/single_subject_109_wf/func_preproc_ses_1_task_restingstate_wf/bold_surf_wf/_hemi_rh/medial_nans

Node inputs:

in_file = ['/mnt/data/loic2/work/fmriprep_wf/single_subject_109_wf/func_preproc_ses_1_task_restingstate_wf/bold_surf_wf/_hemi_rh/sampler/mapflow/_sampler0/rh.fsaverage5.gii']
subjects_dir = <undefined>
target_subject = ['fsaverage5']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1253, in _run_interface
    self.config['execution']['stop_on_first_crash'])))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1128, in _collate_results
    for i, nresult, err in nodes:
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 99, in nodelist_runner
    result = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 369, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/freesurfer.py", line 328, in _run_interface
    newpath=runtime.cwd)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/freesurfer.py", line 463, in medial_wall_to_nan
    darray.data[medial] = np.nan
ValueError: assignment destination is read-only
"
Would you know how to fix it? 
It looks like there was a modification of numpy, isn't it?

Thanks in advance for your help!

### PR DESCRIPTION
**Pull request by effigies**
Fixes #746.

### CODE REVIEW

**Comment by effigies** [comment]
So I dug a bit into our options for finding ways of translating from B64BIN/B64GZ to a bytearray with fewer copies, but at least the out-of-the-box attempts like `BytesIO` + `GzipFile` will make copies internally and seem unlikely to save us much.

On the plus side, data arrays will rarely get larger than a point set (up to 163842x3 float64s) or triangle mesh (~330000x3 int32s), which will each be less than 4MB, so one or two unnecessary copies are unlikely to cause an out-of-memory error, and the XML parsing will probably be more expensive.

That said, if anybody knows some clever tricks, I'm happy to hear them.

This is ready for review. Travis failures will be fixed with #749.

**Comment by pauldmccarthy** [comment]
I tried and failed to fix this issue with `indexed_gzip`, but I'm wrapping the `IndexedGzipFile` class with an `io.BufferedReader` which, regardless of what I do in the `IndexedGzipFile` class, will always return a `bytes` object :(

However, I personally don't need the data to be writeable - the only reason I was bitten by this is because `pyopengl` currently (and unnecessarily) requires writeable arrays.  Personally, I'd be inclined to just return read-only data - if the caller needs the data to be writeable, they can explicitly take on the burden of creating the copy.

But as you said, these arrays aren't very big most of the time, so copying is unlikely to be a bottleneck.

**Comment by effigies** [comment]
@pauldmccarthy Pretty much all of our image types expose writable data arrays, so I'm inclined to call their being read-only a bug.

**Comment by effigies** [comment]
Any further comments/reviews?

**Pull request merged**
