### PR TITLE
ENH: Make imagestats module available on ``import nibabel``

### PR DESCRIPTION
**Pull request by Factral**
this add the import of imagestats to __init__.py

context of imagestats: #952 

Solve #1207

### CODE REVIEW

**Comment by Factral** [comment]
I already run pre-commit but I'm getting this error, any idea why? I did not touch any other file or configuration

image

**Comment by effigies** [comment]
Ah, for the mypy one, you need to run `hatch build --hooks-only`. Or simpler `pip install -e .`.

**Comment by Factral** [comment]
> Ah, for the mypy one, you need to run `hatch build --hooks-only`. Or simpler `pip install -e .`.

thanks!, the error was because i was trying to commit from windows 😂

**Comment by effigies** [comment]
Thanks! The failures are #1209, so unrelated to this.

**Pull request merged**
