### PR TITLE
ENH: adding TRK <=> TCK streamlines conversion scripts

### PR DESCRIPTION
**Pull request by MarcCote**
This PR adds two small scripts to convert streamlines from one format (TRK or TCK) to the other.

We might want to wait for #601.

### CODE REVIEW

**Comment by yarikoptic** [comment]
FWIW #601 is merged now ;-)

**Comment by MarcCote** [comment]
Not sure why the coverage has decreased.

**Comment by effigies** [comment]
@MarcCote Is this ready to go?

**Comment by MarcCote** [comment]
Yes, it is. There is just the coverage that slightly decreases but I don't know why. Let me know if you want me to rebase.

**Comment by effigies** [comment]
LGTM. Will merge this afternoon (EDT) in case anybody wants time to review.

**Pull request merged**
