### PR TITLE
ENH: deprecate Wrapper.get_affine - use affine property

### PR DESCRIPTION
**Pull request by yarikoptic**
To stay inline with the regular interfaces

If there are maintenance releases to happen with python2 support -- this should probably cherry picked there or I could rebase -- should it be maint/2.5.x?

### CODE REVIEW

**Comment by effigies** [comment]
Easiest is to rebase on the maintenance branch. We can still merge that branch into master pretty easily. Can move to a backport approach once that gets painful.

**Comment by yarikoptic** [comment]
> Easiest is to rebase on the maintenance branch.

maint/2.5.x ?

**Comment by yarikoptic** [comment]
ok, tests against master passed. rebased, force pushed and now will change the base in the PR to maint/2.5.x

**Comment by effigies** [comment]
Looks like CI got confused about the changing target branch. Bumped.

**Comment by effigies** [comment]
Thanks, @yarikoptic. Would you mind updating the docstring to note that `affine` is now a property and remove `get_affine`?

On the whole, it looks like the class could use some conforming to the `SpatialImage` API, but I don't want to expand the scope of this PR. I'll open an issue.

**Comment by yarikoptic** [comment]
Sorry @effigies for not reacting, thanks for pushing the tune up!

**Comment by effigies** [comment]
The AppVeyor failures are fixed in #804, so the easiest fix is to merge that and merge or rebase `maint/2.5.x`.

**Comment by yarikoptic** [comment]
please proceed any way you see best fit ;)

**Comment by yarikoptic** [comment]
Sure, why not? ;-)

**Pull request merged**
