### PR TITLE
[WIP] TEST/RF: Increase coverage where easy

### PR DESCRIPTION
**Pull request by effigies**
Just looking through the coverage report for easy fixes. Starting the PR to get a coverage report, to make sure I'm not breaking anything and increasing coverage where I think I am.

I plan to add to this intermittently, but feel free to comment or merge if it looks useful. (If it gets merged, I'll just start another PR next time I do any work of this sort.)

### CODE REVIEW

**Comment by yarikoptic** [comment]
I love when "easy" things become also useful, thank you @effigies ! ;)  here windows/appveyor might have dug out some not closed properly file?  
```
======================================================================
ERROR: nibabel.tests.test_arrayproxy.test_keep_file_open_true_false_invalid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27\lib\site-packages\nibabel\tests\test_arrayproxy.py", line 409, in test_keep_file_open_true_false_invalid
    ArrayProxy(fname, ((10, 10, 10), dtype), keep_file_open='cauto')
  File "c:\python27\lib\site-packages\nibabel\tmpdirs.py", line 76, in __exit__
    return super(InTemporaryDirectory, self).__exit__(exc, value, tb)
  File "c:\python27\lib\site-packages\nibabel\tmpdirs.py", line 48, in __exit__
    self.cleanup()
  File "c:\python27\lib\site-packages\nibabel\tmpdirs.py", line 44, in cleanup
    shutil.rmtree(self.name)
  File "c:\python27\lib\shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 264, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpeni_j8\\testdata'
```

**Comment by effigies** [comment]
Ah. I was hoping this was just a one-off AppVeyor failure that retrying in a couple days would fix.

**Comment by matthew-brett** [comment]
'Fraid not - Windows will be wanting any references to open files deleted before allowing the file (and containing directory) to be deleted...

**Comment by yarikoptic** [comment]
oh right -- we had that too I think -- the fix is "awesome":
https://github.com/datalad/datalad/commit/229bdc677319cde9f53f6a5ee97e36dc67de59d7

**Comment by effigies** [comment]
Hopefully the latency is the only issue. As far as I can see, the file objects should be getting garbage collected.

**Comment by effigies** [comment]
Nope, looks like we've got an open filehandle. @pauldmccarthy Anything stick out to you? Appears to result from me adding a test for `keep_file_open='auto'`.

**Comment by matthew-brett** [comment]
I'll have a go at this one ...

**Comment by matthew-brett** [comment]
Chris - would you mind reverting the last commit, and adding:

```
diff --git a/nibabel/tests/test_arrayproxy.py b/nibabel/tests/test_arrayproxy.py
index d1785351..81416669 100644
--- a/nibabel/tests/test_arrayproxy.py
+++ b/nibabel/tests/test_arrayproxy.py
@@ -381,6 +381,7 @@ def test_keep_file_open_true_false_invalid():
                 x , y, z = [int(c) for c in voxels[i, :]]
                 assert proxy_kfp[x, y, z] == x * 100 + y * 10 + z
                 assert CountingImageOpener.num_openers == 1
+            del proxy_kfp
         # Test that the keep_file_open flag has no effect if an open file
         # handle is passed in
         with open(fname, 'rb') as fobj:
```

I think that fixes it.

**Comment by pauldmccarthy** [comment]
@effigies and @matthew-brett sorry, I missed this conversation. I'll make sure to keep an eye on it in case @matthew-brett's  patch doesn't work...

**Comment by effigies** [comment]
Nice catch. It didn't occur to me to look outside of my changes for the leak...

**Comment by matthew-brett** [comment]
No, nor me, but with a bit of bisect deleting, it showed itself ...

**Comment by effigies** [comment]
Also, Codecov includes `tests/` directories in its coverage. I'd be inclined to exclude them, but don't know if you have a preference one way or the other.

**Comment by matthew-brett** [comment]
I agree, it doesn't make sense to cover the test directories ...

**Comment by matthew-brett** [comment]
The coverage drop just reflects the fact we aren't cheating any more by covering the tests - merging, thanks.

**Pull request merged**
