### PR TITLE
REL: 2.3.0

### LINKED ISSUE #622: 2.3 release?
With current describe being 2.2.1-151-g586c0e07 I thought it might be time to think about the release.  The list of PRs is quite busy with outstanding ones, such as #567.

### LINKED ISSUE #631: ETA for next nibabel release?
Hi @matthew-brett, @effigies and all,

We were wondering when will be the next nibabel release.

We have some issue will loading "large" trk files with last release. The good news is that the fix is already in your master. The issue affects mostly nibabel and dipy windows users. Basically it takes literally for ever to load those files.

Merged PR here
https://github.com/nipy/nibabel/pull/597

### PR DESCRIPTION
**Pull request by effigies**
Open issues/PRs that could go in quickly
--------
* [x] #550 [PR] (Submitter: @effigies; Reviewer: @matthew-brett)
* [x] #561 [PR] (Submitter: @rmarkello; Reviewer: @matthew-brett)
* [x] #606 [PR] (Submitter: @MarcCote)
* [x] #614 [PR] (Submitter: @pauldmccarthy; Reviewer: @effigies @matthew-brett) 
* [x] #615 [PR] (Submitter: @chrispycheng; Reviewer: @yarikoptic)
* [ ] #617 [PR] (Submitter: @chrispycheng; Reviewer: @yarikoptic)
* [ ] #619 [BUG] (Submitter: @larsoner)

Pre-release checklist
--------
* [x] Review the open list of [nibabel issues](https://github.com/nipy/nibabel/issues). Check whether there are outstanding issues that can be closed, and whether there are any issues that should delay the release. Label them!
* [x] Review and update the release notes. Review and update the [Changelog file](https://github.com/nipy/nibabel/blob/master/Changelog).
* [x] Look at [`doc/source/index.rst`](https://github.com/nipy/nibabel/blob/master/doc/source/index.rst) and add any authors not yet acknowledged.
* [x] Use the opportunity to update the [`.mailmap file`](https://github.com/nipy/nibabel/blob/master/.mailmap) if there are any duplicate authors listed from `git shortlog -nse`.
* [x] Check the copyright year in [doc/source/conf.py](https://github.com/nipy/nibabel/blob/master/doc/source/conf.py)
* [x] Refresh the [README.rst](https://github.com/nipy/nibabel/blob/master/README.rst) text from the `LONG_DESCRIPTION` in [`info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) by running `make refresh-readme`.
* [x] Check the dependencies listed in [`nibabel/info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) (e.g. `NUMPY_MIN_VERSION`) and in [`doc/source/installation.rst`](https://github.com/nipy/nibabel/blob/master/doc/source/installation.rst) and in [`requirements.txt`](https://github.com/nipy/nibabel/blob/master/requirements.txt) and [`.travis.yml`](https://github.com/nipy/nibabel/blob/master/.travis.yml). They should at least match. Do they still hold? Make sure nibabel on travis is testing the minimum dependencies specifically.
* [ ] [`nibabel-release-checks`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14)
  * [ ] [`make sdist-tests` errors](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14/steps/shell_7/logs/stdio)
  * [x] [`make check-version-info`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14/steps/shell_9/logs/stdio)
  * [x] [`make check-files`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14/steps/shell_8/logs/stdio)
  * [ ] [`make -C doc doctest`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14/steps/shell_14/logs/stdio)
  * [x] [`python -m compileall .`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14/steps/shell_6/logs/stdio)
  * [x] [`make source-release`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/14/steps/shell_10/logs/stdio)
* [ ] Make sure all tests pass (from the nibabel root directory): `nosetests --with-doctest nibabel`
* [x] Edit [`nibabel/info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) to set `_version_extra` to `''`; commit
* [ ] Build bots
  * [x] [nibabel-py2.7-osx-10.10](https://nipy.bic.berkeley.edu/builders/nibabel-py2.7-osx-10.10/builds/183/steps/shell_6/logs/stdio)
  * [x] [nibabel-bdist32-27](http://nipy.bic.berkeley.edu/builders/nibabel-bdist32-27/builds/211/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist32-33](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-33/builds/192/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist32-34](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-34/builds/197/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist32-35](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-35/builds/119/steps/shell_8/logs/stdio)
  * [ ] nibabel-bdist64-27 [buildslave offline]

Adapted from http://nipy.org/nibabel/devel/make_release.html#release-checklist

Closes #622 
Closes #631

### CODE REVIEW

**Comment by pauldmccarthy** [comment]
Hey @effigies and @matthew-brett , I will try and finish off #614 over the next week.

**Comment by effigies** [comment]
@pauldmccarthy For the sake of having enough time to properly test and release before OHBM, I would like to avoid merging anything for 2.3.0 after tomorrow.

Finishing this off soon would obviously be welcome, and I would support a micro-release once it is in, as I think deprecating that API sooner than later would be a good move. Just wanted to comment, to calibrate your expectations, here.

**Comment by effigies** [comment]
Also, part of the short turnaround here has to do with the holiday this past Monday. I was mentally in Tuesday, yesterday, so I didn't realize I was giving only 2 days warning.

**Comment by pauldmccarthy** [comment]
@effigies Ok ... I have just moved house (relocated across the country), but will do my best to get it in a mergable state over the next couple of days!

**Comment by effigies** [comment]
@matthew-brett There seem to be issues with the [nibabel-py2.7-osx-10.10](https://nipy.bic.berkeley.edu/builders/nibabel-py2.7-osx-10.10) and [nibabel-bdist64-27](https://nipy.bic.berkeley.edu/builders/nibabel-bdist64-27/) buildbots. On the former, pip has been failing since Mar 29. On the latter, the buildslave has been down since at least Apr 13.

**Comment by matthew-brett** [comment]
Sorry about the buildbots - I'm not in that office any more so it's harder to maintain them.

I fixed the OSX build.  I'll ask someone to reboot the Windows machine that appears to be down.

**Comment by yarikoptic** [comment]
I would really love to see https://github.com/nipy/nibabel/pull/615 merged since it is the right thing to do ;-) BUT I've stumbled on difficulty to make doctests to not crash while trying to import that fuse-based dicomfs submodule which wouldn't be present on some systems... any hints would be super useful

**Comment by nibotmi** [comment]
:umbrella: The latest upstream changes (presumably #550) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by yarikoptic** [comment]
@effigies tested a few reverse depends on stretch (on sid - there are issues we need to fix in them) -- all good. The only one is dcmstack for which we fixed the issue in nibabel for deterministic slice order magic -- yet to upload fresh release (0.7.0) so could be ignored I think (alternatively, I could test again or fix up later)

```shell
neurodebian@smaug ..uilds/nibabel/2.3.0+git432-g58418066-1 % cat nibabel_2.3.0+git432-g58418066-1~nd90+1_amd64.testrdepends.nd+debian-stretch.summary

Testing builds against nibabel_2.3.0+git432-g58418066-1~nd90+1.dsc
cfflib_2.0.5-2.dsc                                 ok      ok
dcmstack_0.6.2+git33-gb43919a.1-1.dsc              ok   FAILED /home/neurodebian/deb/builds/nibabel/2.3.0+git432-g58418066-1/nibabel_2.3.0+git432-g58418066-1~nd90+1_amd64.testrdepends.nd+debian-stretch/srcs/new/dcmstack_0.6.2+git33-gb43919a.1-1_amd64.build
nitime_0.7-1.dsc                                   ok      ok
pymvpa2_2.6.0-1.dsc                                ok      ok
pysurfer_0.7-2.1~deb9u1.dsc                        ok      ok
```

**Pull request merged**
