### PR TITLE
Require setuptools, nibabel/tests/test_init.py, nibabel/__init__.py, nibabel/testing/__init__.py import pkg_resources

### PR DESCRIPTION
**Pull request by hrnciar**

### CODE REVIEW

**Comment by effigies** [comment]
Good catch. Do we have a minimum version of setuptools needed?

**Comment by hrnciar** [comment]
Actually, it's pretty old. It's part of setuptools since v.0.6 that was released in 2005.
https://github.com/pypa/setuptools/commit/ee8b1aa7f26f8c423c53b50bc743d8a725bbab5a

**Comment by effigies** [comment]
Cool, thanks. Can you go ahead and run `tools/update_requirements.txt` and commit the results?

**Comment by hrnciar** [comment]
Sure thing, I have force pushed updated files into PR.

**Review by effigies — APPROVED** [review]
Great, thanks.

**Pull request merged**
