### PR TITLE
FIX: Interpret empty string in SliceThickness DICOM field as missing (default to 1)

### PR DESCRIPTION
**Pull request by mattcieslak**
I was running into an issue where sometimes the value for SliceThickness was an empty string instead of None. I'm not sure if this is the right place to add the change, though.

### CODE REVIEW

**Comment by effigies** [comment]
Hi, sorry for the slow response. Is there any chance of providing a test DICOM file that will hit this code path?

**Comment by effigies** [comment]
Hi @mattcieslak, just wanted to see if you have a test file that exhibits this property? Synthetic or anonymized would both work fine.

**Comment by mattcieslak** [comment]
I'll check to see if I can find this again, I think it might have been a non-image dicom that was causing the trouble.

**Comment by effigies** [comment]
Hi @mattcieslak, sorry to be a nuisance, but I'm going to try to release next Monday, so it'd be great to get this in ASAP.

**Comment by mattcieslak** [comment]
Found the file and am checking with the study owners what the sharing policy is. I'm thinking this might just be a corrupt dicom because the rest of the files from that series have valid numbers for slice thickness

**Comment by effigies** [comment]
Awesome. Thanks for your patience on this. (Failing tests are the usual AppVeyor weirdness.)

**Pull request merged**
