### PR TITLE
Pre-release book-keeping

### PR DESCRIPTION
**Pull request by effigies**
#540 prompted me to follow up on #515 and get the docs up-to-date.

I also hope to see a new release soon. Let me know if there's anything else I can do to help it along.

If at all possible, I think #526 would be great to have in before the release.

### CODE REVIEW

**Comment by effigies** [comment]
@pauldmccarthy Let me know if you prefer to be credited with another version of your name.

@fepegar Just want to verify that I got your name correct. Based on a [StackOverflow profile](https://stackoverflow.com/users/3956024/fepegar) with the same username, I believe [this](https://www.linkedin.com/in/fernandoperezgarcia) is you?

@R3DDY97 Do you have a name/alias you'd prefer to be credited as?

**Comment by fepegar** [comment]
Hi @effigies 
Yes, that's me. Thank you!

**Comment by pauldmccarthy** [comment]
Hi @effigies, looks great - thanks!

**Comment by R3DDY97** [comment]
Hi @effigies 
i would  prefer to be credited as  **Dr. Reddy** 
Thanks

**Comment by effigies** [comment]
@R3DDY97 Given that we haven't included "Dr." for any of the other authors with doctorates, thus far, I've added you as "Venky Reddy". I hope this is acceptable.

**Comment by R3DDY97** [comment]
@effigies 
Yeah **That's OK fine ..**

btw mine is not Doctorate's Dr (PhD)
Its Physician Dr. got after medical Graduation..

**Pull request merged**
