### PR TITLE
MRG: delay set of gifti parser for circular import

### PR DESCRIPTION
**Pull request by matthew-brett**
The GiftiImage class sets GiftiImageParser as a class attribute, but the GiftiImageParser needs to import and use the GiftiImage class.  So, delay the setting of the parser class attribute until GiftiImage is fully defined, and therefore usable from `parse_fast_gifti.py`, which defines GiftiImageParser.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Closes #405 - if accepted ...

**Comment by effigies** [comment]
Test fails before and succeeds after, so seems good as long as nose keeps doing things lexically.

LGTM.

**Comment by matthew-brett** [comment]
Chris - OK to merge this one?

**Comment by effigies** [comment]
:+1:

**Comment by matthew-brett** [comment]
Thanks Chris.

**Pull request merged**
