### PR TITLE
REL: 2.5.0

### LINKED ISSUE #781: Build failure with numpy 1.17.0
I am getting the following error when running the unittests with with numpy 1.17.0.  It doesn't happen with numpy 1.16

```
======================================================================
ERROR: nibabel.tests.test_volumeutils.test_a2f_non_numeric
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/abuild/rpmbuild/BUILD/nibabel-2.4.1/nibabel/tests/test_volumeutils.py", line 702, in test_a2f_non_numeric
    arr.astype(float)
TypeError: Cannot cast array from dtype([('f1', '<f4'), ('f2', '<i2')]) to dtype('float64') according to the rule 'unsafe'
```

### PR DESCRIPTION
**Pull request by effigies**
About time for our trimesterly minor release.

Open issues/PRs that could go in quickly
--------
* [ ] #712 [BUG] (Submitter: @ltetrel)
* [x] #775 [BUG] (Submitter: @sanjayankur31)
* [x] #776 [BUG] (Submitter: @idoimaging)

Closes #781.

Pre-release checklist
--------
* [x] Review the open list of [nibabel issues](https://github.com/nipy/nibabel/issues). Check whether there are outstanding issues that can be closed, and whether there are any issues that should delay the release. Label them!
* [x] Review and update the release notes. Review and update the [Changelog file](https://github.com/nipy/nibabel/blob/master/Changelog).
* [x] Look at [`doc/source/index.rst`](https://github.com/nipy/nibabel/blob/master/doc/source/index.rst) and add any authors not yet acknowledged.
* [x] Use the opportunity to update the [`.mailmap file`](https://github.com/nipy/nibabel/blob/master/.mailmap) if there are any duplicate authors listed from `git shortlog -nse`.
* [x] Check the copyright year in [doc/source/conf.py](https://github.com/nipy/nibabel/blob/master/doc/source/conf.py)
* [x] Refresh the [README.rst](https://github.com/nipy/nibabel/blob/master/README.rst) text from the `LONG_DESCRIPTION` in [`info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) by running `make refresh-readme`.
* [x] Check the dependencies listed in [`nibabel/info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) (e.g. `NUMPY_MIN_VERSION`) and in [`doc/source/installation.rst`](https://github.com/nipy/nibabel/blob/master/doc/source/installation.rst) and in [`requirements.txt`](https://github.com/nipy/nibabel/blob/master/requirements.txt) and [`.travis.yml`](https://github.com/nipy/nibabel/blob/master/.travis.yml). They should at least match. Do they still hold? Make sure nibabel on travis is testing the minimum dependencies specifically.
* [x] Make sure all tests pass (from the nibabel root directory): `nosetests --with-doctest nibabel`
* [x] Edit [`nibabel/info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) to set `_version_extra` to `''`; commit

Adapted from http://nipy.org/nibabel/devel/make_release.html#release-checklist

### CODE REVIEW

**Comment by effigies** [comment]
I'm pushing off #712 for now, and we're ready for release.

@yarikoptic Care to run your tests for Debian?
@sanjayankur31 And Fedora?

**Comment by sanjayankur31** [comment]
> @sanjayankur31 And Fedora?

Looks good. Here is a successful test build on s390x:
https://koji.fedoraproject.org/koji/taskinfo?taskID=36761683

All tests pass properly. Thanks very much! :champagne:

**Comment by yarikoptic** [comment]
running across neurodebians ATM
for me also succeeded on s390 debian sid

**Comment by effigies** [comment]
Great! Thanks for the confirmation.

**Pull request merged**
