### PR TITLE
TEST: Replace dict literal with set()

### PR DESCRIPTION
**Pull request by effigies**
Thanks to @musicinmybrain for finding and reporting this.

Closes gh-1382.

### CODE REVIEW

**Comment by effigies** [comment]
@musicinmybrain Does it make sense just to patch this for now? It does not seem entirely worth making a release for a bug in test code.

**Comment by musicinmybrain** [comment]
I’m perfectly happy just to backport the patch until the next release, especially since it’s just a minor testing issue. If you give me about five minutes, I’ll test the patch in Fedora and report back.

**Comment by effigies** [comment]
@yurivict @penguinpee You're likely to hit this, too.

@TheChymera @sanjayankur31 @ashgillman Are you still packaging for Gentoo, CentOS and Nix? If so, let me know if a patch is okay or if you need a release. If not, can you @ your successors?

**Comment by musicinmybrain** [comment]
> @TheChymera @sanjayankur31 @ashgillman Are you still packaging for Gentoo, CentOS and Nix? If so, let me know if a patch is okay or if you need a release. If not, can you @ your successors?

I’m assisting @sanjayankur31 with the Fedora package, which is how I encountered this. There is no corresponding [EPEL](https://docs.fedoraproject.org/en-US/epel/) package (which is how it would be made available to CentOS users). It’s probably possible to get it working there, but [NeuroFedora](https://docs.fedoraproject.org/en-US/neurofedora/overview/) packages are generally only added to EPEL at their primary maintainers’ discretion or [upon request](https://docs.fedoraproject.org/en-US/epel/epel-package-request/), rather than by default.

**Pull request merged**
