### PR TITLE
MAINT: switch to codecov for coverage report

### PR DESCRIPTION
**Pull request by matthew-brett**
Scipy, Pandas, scikit-image use codecov.

Example output (via travis-ci):
https://codecov.io/github/matthew-brett/nibabel/nibabel?ref=c576b5d459c12ae8e052bd21fd27f5faff336e46

### CODE REVIEW

**Comment by yarikoptic** [comment]
No need to switch, you can have both afaik... At least I just did that for datalad and fail2ban.
Also it presumably (didn't with for me yet) has extensions for browsers to highlight coverage straight while browsing github PR etc... Should be cool... I like it more overall but still keep coveralls enabled since seems to not hurt

**Comment by matthew-brett** [comment]
There's a browser extension for looking at coverage on github : https://codecov.io/#features

**Comment by matthew-brett** [comment]
Do you then have both coveralls and codecov enabled in the github status reports?

**Comment by yarikoptic** [comment]
in the status report only coveralls appears but both insert status boxes above, see e.g. https://github.com/datalad/datalad/pull/377

**Comment by matthew-brett** [comment]
Any benefit to keeping both?  Has there been a case where the coveralls result was more useful?

**Comment by yarikoptic** [comment]
Fwiw not yet. Redundant free service though is good for resilience against failures of one of the two

**Comment by matthew-brett** [comment]
Fair enough - I left coveralls in.

**Comment by matthew-brett** [comment]
Will merge tomorrow unless I hear otherwise.

**Pull request merged**
