### PR TITLE
2.2.0 release prep

### LINKED ISSUE #540: release?
Any plans for cutting a new release? I'd love to have the CIFTI support.

### LINKED ISSUE #554: streamlines module can't be found
Hi there, 

I'm trying to import the streamlines module in a Python script, but it tells me that there's no module named streamlines.

I'm using Python 2.7 on Anaconda on a Win32. After I import the nibabel library, I try:
from nibabel.streamlines import ArraySequence as Streamlines

What I get is:
ImportError: No module called streamlines.

Sorry, can't copy the code from my MinGW32.

Hope you can help

### PR DESCRIPTION
**Pull request by effigies**
Minor version increment. Fixed a FreeSurfer test that depended on FreeSurfer < v6.0.0.

Closes #540

Open issues/PRs that could go in quickly
--------
* [ ] #524 
* [ ] #550
* [ ] #554
* [x] #562
* [ ] Follow-up edits to https://github.com/nipy/nibabel/pull/552#issuecomment-331950557?

Pre-release checklist
--------
* [x] Review the open list of [nibabel issues](https://github.com/nipy/nibabel/issues). Check whether there are outstanding issues that can be closed, and whether there are any issues that should delay the release. Label them!
* [x] Review and update the release notes. Review and update the [Changelog file](https://github.com/nipy/nibabel/blob/master/Changelog).
* [x] Look at [`doc/source/index.rst`](https://github.com/nipy/nibabel/blob/master/doc/source/index.rst) and add any authors not yet acknowledged.
* [x] Use the opportunity to update the [`.mailmap file`](https://github.com/nipy/nibabel/blob/master/.mailmap) if there are any duplicate authors listed from `git shortlog -nse`.
* [x] Check the copyright year in [doc/source/conf.py](https://github.com/nipy/nibabel/blob/master/doc/source/conf.py)
* [x] Refresh the [README.rst](https://github.com/nipy/nibabel/blob/master/README.rst) text from the `LONG_DESCRIPTION` in [`info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) by running `make refresh-readme`.
* [x] Check the dependencies listed in [`nibabel/info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py) (e.g. `NUMPY_MIN_VERSION`) and in [`doc/source/installation.rst`](https://github.com/nipy/nibabel/blob/master/doc/source/installation.rst) and in [`requirements.txt`](https://github.com/nipy/nibabel/blob/master/requirements.txt) and [`.travis.yml`](https://github.com/nipy/nibabel/blob/master/.travis.yml). They should at least match. Do they still hold? Make sure nibabel on travis is testing the minimum dependencies specifically.
* [ ] [`nibabel-release-checks`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11)
  * [ ] [`make sdist-tests` errors](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11/steps/shell_7/logs/stdio)
  * [x] [`make check-version-info`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11/steps/shell_9/logs/stdio)
  * [x] [`make check-files`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11/steps/shell_8/logs/stdio)
  * [ ] [`make -C doc doctest`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11/steps/shell_14/logs/stdio)
  * [x] [`python -m compileall .`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11/steps/shell_6/logs/stdio)
  * [x] [`make source-release`](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/11/steps/shell_10/logs/stdio)
* [x] Make sure all tests pass (from the nibabel root directory): `nosetests --with-doctest nibabel`
* [x] Edit [`nibabel/info.py`](https://github.com/nipy/nibabel/blob/master/nibabel/info.py)) to set `_version_extra` to `''`; commit
* [x] Build bots
  * [x] [nibabel-py2.7-osx-10.10](https://nipy.bic.berkeley.edu/builders/nibabel-py2.7-osx-10.10/builds/137/steps/shell_6/logs/stdio)
  * [x] [nibabel-bdist32-27](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-27/builds/180/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist32-33](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-33/builds/161/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist32-34](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-34/builds/167/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist32-35](https://nipy.bic.berkeley.edu/builders/nibabel-bdist32-35/builds/89/steps/shell_8/logs/stdio)
  * [x] [nibabel-bdist64-27](https://nipy.bic.berkeley.edu/builders/nibabel-bdist64-27/builds/133/steps/shell_8/logs/stdio)

Adapted from http://nipy.org/nibabel/devel/make_release.html#release-checklist

### CODE REVIEW

**Comment by effigies** [comment]
@matthew-brett Do you have time to look at the [`make sdist-tests` errors](https://nipy.bic.berkeley.edu/builders/nibabel-release-checks/builds/7/steps/shell_7/logs/stdio)? Looking at the code, I don't see why those failed.

Apart from open issues to decide whether to work on, that's the only hang-up I have for release.

**Comment by effigies** [comment]
Now two failing chunks of `nibabel-release-checks`. Any thoughts? I've tried updating the `np.printoptions` in `nifti_images.rst`, but that didn't resolve the issue.

**Comment by effigies** [comment]
@matthew-brett Stuck here. If you can find some time, I could use some help getting this release out.

**Comment by matthew-brett** [comment]
Sorry Chris - got a bit snowed under.  Sorry too, I should have deleted those from the release doc - when I wrote those checks, we were doing much much less automated testing - and they were before we had scripts being testing.  So I think we can ignore those errors.   And we should remove those checks.

**Comment by effigies** [comment]
Sounds good. I'll merge this and release today, if there are no other issues.

**Comment by matthew-brett** [comment]
Are you planning to release without the image slicing?  I can try to get to this later today.

**Comment by effigies** [comment]
Can go either way. Obviously would be a nice feature to have, but if you think it needs more time to settle the API and test before it's in an official release, that's fine too.

If you want to see how close it is to ready, we can decide whether to put it in first.

**Comment by matthew-brett** [comment]
Let's leave the image slicing for the next release - and plan for another release in a month or so?

**Comment by effigies** [comment]
Sounds good.

**Pull request merged**
