### PR TITLE
ENH: reading PAR headers from NIfTI extensions

### PR DESCRIPTION
**Pull request by matthew-brett**
A small function to fetch PARHeader object from PAR headers recorded in NIfTI
comment extensions.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Ready for review from your end? cc @mrjeffs in case you don't follow the repo, you'd probably be interested in this

**Comment by matthew-brett** [comment]
Yes, ready for review...

**Comment by Eric89GXL** [comment]
LGTM -- looks reasonable, is reasonably tested, and tests pass. +1 for merge from me.

**Comment by matthew-brett** [comment]
I added a little more flexibility - any more comments?

**Comment by Eric89GXL** [comment]
LGTM

**Pull request merged**
