### PR TITLE
DOC: Attempt to find versioneer version when building docs

### LINKED ISSUE #869: BUG: API docs fail when nibabel.info.VERSION doesn't match nibabel.__version__
Currently this page has no links:

https://nipy.org/nibabel/api.html#api

Found by seeing that our `intersphinx` links have [broken in CIs](https://circleci.com/gh/mne-tools/mne-python/17705).

### PR DESCRIPTION
**Pull request by effigies**
Closes #869.

Start by trying to get CI to fail pre-fix. It currently is failing silently.

Edit: Also tracked down various warnings emitted during doc build. Some remain:

```
Running Sphinx v2.2.1
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 115 source files that are out of date
updating environment: [new config] 115 added, 0 changed, 0 removed
/System/Volumes/Data/anaconda3/envs/nibabel-dev/lib/python3.7/importlib/__init__.py:127: UserWarning: The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment                                                                        
Please use with caution.  We would be grateful for your help in improving them
  return _bootstrap._gcd_import(name[level:], package, level)
reading sources... [100%] tutorials                                                                                                                                                                                                                                                   
/Users/markiewicz/Projects/nibabel/nibabel/cifti2/__init__.py:docstring of nibabel.cifti2.rst:5: WARNING: autosummary: stub file not found 'nibabel.cifti2.cifti2'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/cifti2/__init__.py:docstring of nibabel.cifti2.rst:5: WARNING: autosummary: stub file not found 'nibabel.cifti2.cifti2_axes'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/gifti/__init__.py:docstring of nibabel.gifti.rst:5: WARNING: autosummary: stub file not found 'nibabel.gifti.giftiio'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/gifti/__init__.py:docstring of nibabel.gifti.rst:5: WARNING: autosummary: stub file not found 'nibabel.gifti.gifti'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/nicom/__init__.py:docstring of nibabel.nicom.rst:5: WARNING: autosummary: stub file not found 'nibabel.nicom.csareader'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/nicom/__init__.py:docstring of nibabel.nicom.rst:5: WARNING: autosummary: stub file not found 'nibabel.nicom.dicomreaders'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/nicom/__init__.py:docstring of nibabel.nicom.rst:5: WARNING: autosummary: stub file not found 'nibabel.nicom.dicomwrappers'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/nicom/__init__.py:docstring of nibabel.nicom.rst:5: WARNING: autosummary: stub file not found 'nibabel.nicom.dwiparams'. Check your autosummary_generate setting.
/Users/markiewicz/Projects/nibabel/nibabel/nicom/__init__.py:docstring of nibabel.nicom.rst:5: WARNING: autosummary: stub file not found 'nibabel.nicom.structreader'. Check your autosummary_generate setting.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/markiewicz/Projects/nibabel/doc/source/devel/bv_formats.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/devel/data_pkg_discuss.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/devel/data_pkg_uses.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/devel/image_design.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/devel/scaling.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/installing_data.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/notebooks/index.rst: WARNING: document isn't included in any toctree
/Users/markiewicz/Projects/nibabel/doc/source/old/ioimplementation.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
/System/Volumes/Data/anaconda3/envs/nibabel-dev/lib/python3.7/site-packages/sphinx/transforms/post_transforms/compat.py:45: RemovedInSphinx30Warning: math node for Sphinx was replaced by docutils'. Please use ``docutils.nodes.math`` instead.                                     
  RemovedInSphinx30Warning)
```

### CODE REVIEW

**Comment by effigies** [comment]
I think this should be pretty uncontroversial. A review of the remaining errors would be appreciated.

* @matthew-brett I'm guessing `/System/Volumes/Data/anaconda3/envs/nibabel-dev/lib/python3.7/site-packages/sphinx/transforms/post_transforms/compat.py:45: RemovedInSphinx30Warning: math node for Sphinx was replaced by docutils'. Please use ``docutils.nodes.math`` instead.                                     
  RemovedInSphinx30Warning)` is `texext`-related, but switching to `docutils.nodes.math` in a fork of `texext` didn't resolve the warning. Any thoughts?

* The autosummary errors don't seem to be resolvable without changing the docs. My guess is we can get around this by using more bog-standard `apidoc`, but I don't have the energy to tackle that at the moment.

* Should any of the orphaned files be added to some ToC? If not, I think we can add `.. orphan:` or similar directive to clear the warning.

**Comment by matthew-brett** [comment]
I am not sure where that warning comes from - but I'm getting the same warning in daily testing of texext : https://travis-ci.org/matthew-brett/texext/jobs/658565402#L441

**Comment by matthew-brett** [comment]
I just uploaded another release of texext, with a related fix from a while ago - does it help?

**Comment by effigies** [comment]
Nope. Still getting the warning. Looks like they've removed the compatibility in `master`. I can try upgrading sphinx and seeing if that breaks something informative.

**Comment by effigies** [comment]
Okay. This is an improvement and resolve an issue blocking a bug-fix release. Additional improvements can come later.

**Pull request merged**
