### PR TITLE
FIX: properly handle V4 .PAR files with diffusion info

### PR DESCRIPTION
**Pull request by grlee77**
This PR fixes a bug in `get_bvals_bvecs` for V4 .PAR files (the bug is only present for V4, not the more recent V4.1 or V4.2).  In V4, the `diffusion` field does not exist and the `bvecs` cannot be determined.

### CODE REVIEW

**Comment by grlee77** [comment]
apologies... should have tested properly before uploading.  I forgot that `image_defs` is a recarray and not a dictionary.  will upload a fix later this evening

**Comment by matthew-brett** [comment]
Thanks - looks good to me.

**Comment by grlee77** [comment]
I can rebase to a single commit if you prefer.

**Comment by matthew-brett** [comment]
It's fine as is - was waiting to see if anyone else wanted to say something, but looks like no - merging.

**Pull request merged**
