### PR TITLE
FIX: Set MRS type to Nifti1Extension for backwards compatibility

### PR DESCRIPTION
**Pull request by effigies**
cc @wtclarke

### CODE REVIEW

**Comment by wtclarke** [comment]
Does `Nifti1Extension` still have the .json() methods? I've just updated the nifti-mrs package to use the new interface. So if the new methods aren't available for this, then I'm happy to just make the changes on my side and not have this fix.

**Comment by effigies** [comment]
Yes, `Nifti1Extension` subclasses `NiftiExtension[bytes]` so `_mangle()` and `_unmangle()` are just identity functions, as was the previous default. The purpose of splitting the classes was so that new subclasses could derive from the base class and declare their types correctly.

**Comment by wtclarke** [comment]
Great, I see now, I was getting confused between `Nifti1Extension` and `Nifti1Extensions`. Thanks for the fix.

**Comment by effigies** [comment]
I guess with the problem solved on your end, we can take a minute to think about how you would like to evolve.

If you would like to offload more of your logic into nibabel and use a `NiftiExtension` directly, then it's possible that creating a `JSONExtension` subclass would make more sense. That would allow `ext.get_object()` to return a cached value that you can mutate. When it's time to save to a new image, that object will override the original `bytes` content.

If read-only access is all you want, then this PR will at least get you back what you had, without users having to upgrade your package if they upgrade nibabel. In practice, though, I expect most people just install the latest versions, and so making this release or not will impact very few people.

**Comment by effigies** [comment]
Well, regardless of the long-term path forward, this has the potential to reduce pain and doesn't make changing in the future harder.

**Comment by wtclarke** [comment]
Hi @effigies, Thanks for this fix. Sorry for the slow reply, four new starters in the group has me rushing about this week. For now I'm happy to keep the logic on my side.

**Pull request merged**
