### PR TITLE
MRG: test fixes and doc updates for multiframe code

### PR DESCRIPTION
**Pull request by matthew-brett**
Fixes to some new test failures at : https://travis-ci.org/matthew-brett/nibabel/builds/121846880

More links to sections and diagrams on multi-frame / enhanced MR image
IOP.

Follow-up to PR #439.

### CODE REVIEW

**Comment by matthew-brett** [comment]
@embaker - I found some small stuff that I hadn't spotted, that needed cleaning up.

**Comment by effigies** [comment]
LGTM. Is there a reason that PRs are no longer built on the nipy Travis account?

**Comment by matthew-brett** [comment]
Hmm - good question about travis-ci and PRs - it seems it got turned off somehow - I turned it back on.

**Comment by matthew-brett** [comment]
@embaker - any comment here before I merge?

**Comment by matthew-brett** [comment]
I'll merge to make it easier to test other PRs - bit please do add any comments here, I'll address them with another PR.

**Comment by embaker** [comment]
No comments. Looks good to me.

**Pull request merged**
